### ISSUE TITLE
Python 3 compatibility integration

### ISSUE THREAD

**Issue by jbecke** [gabrielStanovsky/oie-benchmark#10]
I've converted the scripts to Python 3 over at https://github.com/NPCai/oie-benchmark. Let me know if and how you'd want this integrated @gabrielStanovsky, whether into master or a new branch potentially.

**Comment by gabrielStanovsky** [comment]
Hi @jbecke, thank you very much!
I'd be glad to integrate this into a separate "Python 3"  branch on the main fork.
Can you try to open a pull request for that? 
Please let me know if you can do that, or if you need me to open a branch for that on my fork first.

Thanks again!

**Comment by jbecke** [comment]
Sure, and yes it seems I need you to open up a new branch on your fork @gabrielStanovsky

**Comment by gabrielStanovsky** [comment]
I opened one, called `python3`
https://github.com/gabrielStanovsky/oie-benchmark/tree/python3

**Comment by jbecke** [comment]
I've made PR #11. I made it from a different repo than mentioned above because I had some extra changes in that one relevant to my research. I've confirmed that the py3 PR curve is the same as the py2 PR curve.

**Comment by gabrielStanovsky** [comment]
Addressed in PR #11 .
