### ISSUE TITLE
A possible mistake in benchmark.py

### ISSUE THREAD

**Issue by zhanjunlang** [gabrielStanovsky/oie-benchmark#12]
In line 56~58,
```python
for goldEx in goldExtractions:   
    unmatchedCount += len(goldExtractions)
    correctTotal += len(goldExtractions)
```
Maybe the for loop is not needed since by doing the for loop you count  `len(goldExtractions)* len(goldExtractions)` times for `unmatchedCount` and `correctTotal` but only `len(goldExtractions)` times are enough for both.

**Comment by gabrielStanovsky** [comment]
Fixed by #16
