### ISSUE TITLE
Different Sentences in raw_sentences/all.txt and oie_corpus/all.oie

### ISSUE THREAD

**Issue by SakshiSaini17092** [gabrielStanovsky/oie-benchmark#18]
I am working on a research project on knowledge representation. I wanted to
use your benchmark for evaluation purposes.

I have cloned the repository and downloaded the dataset, but I am facing issues.
Many sentences in `all.txt` in the `raw_sentences` folder are not there in
the `all.oie` file in `oie_corpus` folder.

Can you please help me in figuring this out?
Is the dataset updated? If yes then how can I test it now as the
`all.oie` is still pointing to old dataset?

I have also ran the difference checker there is only 2 percent overlap between 2 files.
Please help me!
I need dataset ASAP.

**Comment by gabrielStanovsky** [comment]
Hi @SakshiSaini17092, how did you obtain `oie_corpus/all.oie`?

**Comment by SakshiSaini17092** [comment]
After running this `./create_oie_corpus.sh` it created it automatically.

**Comment by gabrielStanovsky** [comment]
I see, thanks for bringing this to my attention. I think that this is an issue with the `all.txt` being out of synch. can you use `all.oie` for your purposes? E.g., to report number on?

**Comment by SakshiSaini17092** [comment]
Yes, I find a way around to use the benchmark for my need. It would be better for anyone who is using the benchmark if you update all.txt.
Thank you!

**Comment by gabrielStanovsky** [comment]
Awesome! will do. good luck :)
