### ISSUE TITLE
Add minimal required nltk version to README

### ISSUE THREAD

**Issue by tbsflk** [gabrielStanovsky/oie-benchmark#2]
I ran `create_oie_corpus.sh` on another machine and had problems with python hanging when loading the qa-srl files. For every line, it got slower, and actually never finished.

I figured out that the script spent most of the time loading the nltk PoS tagging model. I had nltk 3.1 installed. After updating to 3.2.1, it worked without problems. So, there seems to be an issue in the PoS tagger of older nltk versions.

It might be helpful to add a minimal required version of nltk to the README.

**Comment by gabrielStanovsky** [comment]
Interesting, I only use NLTK for its POS tagging and indeed I also have 3.2.1 on my machine. 
I wonder why it's hanging on an older version.
I'll add a minimal requirements file and also start an FAQ section. 

Thanks!

**Comment by gabrielStanovsky** [comment]
Added (see readme)
