### ISSUE TITLE
Problems in Eval

### ISSUE THREAD

**Issue by monstertony** [gabrielStanovsky/oie-benchmark#8]
Hi,

I output my results as clausie format. But when I did evaluation, I just got one pair of percision and recall value. Can you please tell me what should be the right clausie format?

Thanks in advance!

**Comment by gabrielStanovsky** [comment]
Hi @monstertony, 
Can you please post the commands you ran, and, if possible, also point me to your data files?

Thanks!

**Comment by monstertony** [comment]
Hi,

Thanks so much for quick reply. 

`python benchmark.py --gold=./oie_corpus/all.oie --out=eval/your_output.dat --clausie=./systems_output/your_output.txt`

I used this command line.

`$ 100 million issue of collateralized mortgage obligations is being offered in four classes by a Morgan Stanley group .
1	"$ 100 million issue"	"of"	"collateralized mortgage obligations"	100
1	"in four classes"	"by"	"a Morgan Stanley group"	100
1	"$ 100 million issue of collateralized mortgage obligations"	"is being offered"	"in four classes by a Morgan Stanley group"	100
11 million copies of the flyer were distributed to the public via an 85-newspaper distribution chain .
2	"11 million copies"	"of"	"the flyer"	100
2	"the public"	"via"	"an 85-newspaper distribution chain"	100
2	"11 million copies of the flyer"	"were distributed to"	"the public via an 85-newspaper distribution chain"	100`

Here are my output examples. I didn't set up the confident score, so I just give them all 100.

Thanks so much!

**Comment by monstertony** [comment]
This is my data files:

[https://drive.google.com/file/d/1PYq3-fgnlF8goM1b5z4krXRJyb8olUpg/view?usp=sharing](url)

**Comment by gabrielStanovsky** [comment]
So ```benchmark.py``` should output the precision-recall performance at different confidence thresholds, in a list of tuples. Then ```pr_plot.py``` can plot that into a graph.
However, since you have a single precision score of 100 for all extractions, I think that a single P-R score is the expected output, as there are no different threshold in the data.

Can you please try varying the confidence in your input (even randomly, for now) and see whether you get different P-R values?

Thanks

**Comment by monstertony** [comment]
Thank so much for your help! I will try your suggestion. If I get the results, I will let you know.

**Comment by gabrielStanovsky** [comment]
Sure thing, let me know :)

**Comment by monstertony** [comment]
Hi,

It works. Really thanks for your help! Can I also ask how you get the confident score? Cause I didn't find clausie's paper mentioned about it. Or it's in your paper?

Thanks again!!!

**Comment by gabrielStanovsky** [comment]
Great!
If I remember correctly, ClausIE indeed doesn't provide a confidence score, but does use Stanford parser, which outputs a confidence score, which is what I used (normalized) for each extraction.
It's not perfect, but hopefully a good approximation.

Please let me know if I can close this issue.

**Comment by monstertony** [comment]
Yes, you can close this issue now. Thanks again for your help!!!
