### ISSUE TITLE
A few comments on installation

### ISSUE THREAD

**Issue by jloveric** [gabrielStanovsky/oie-benchmark#9]
I needed to install a few nltk tools

import nltk
nltk.download('averaged_perceptron_tagger') 
nltk.download('punkt')

Also it seems the file names at
https://dada.cs.washington.edu/qasrl/#dataset

have changed, from propbank* to newswire*

**Comment by gabrielStanovsky** [comment]
@jloveric thanks for the heads-up!
Any chance you can make a pull request with your changes?

If that's inconvenient for you, I can address this in the next couple of days.

Thanks!

**Comment by jloveric** [comment]
Possibly, I may try and produce a one command installation for this.  Not sure if it's going to happen immediately though.
